[package]
name = "ear"
version = "0.1.0"
edition = "2021"

[dependencies]
utralib = { version = "0.1.27", optional = true, default-features = false }
ticktimer = { package = "xous-api-ticktimer", version = "0.9.70" }
xous = "0.9.70"
log-server = { package = "xous-api-log", version = "0.1.69" }
log = "0.4.14"
bao1x-hal = { git = "https://github.com/betrusted-io/xous-core", rev = "aee40a797af372b6debf938d2902b03d1002e8a2", features = ["std"] }
bao1x-api = { git = "https://github.com/betrusted-io/xous-core", rev = "aee40a797af372b6debf938d2902b03d1002e8a2" }
bao1x-hal-service = { git = "https://github.com/betrusted-io/xous-core", rev = "aee40a797af372b6debf938d2902b03d1002e8a2" }
usb-bao1x = { git = "https://github.com/betrusted-io/xous-core", rev = "aee40a797af372b6debf938d2902b03d1002e8a2" }

triangel-shared = { path = "../shared" }

[profile.release]
# The soft-float intrinsics live in compiler_builtins, so they only inline across
# the crate boundary with LTO on. This loop is 98k of them per frame.
lto = true
codegen-units = 1

[patch.crates-io]
getrandom = { git = "https://github.com/betrusted-io/xous-core", rev = "aee40a797af372b6debf938d2902b03d1002e8a2" }

[features]
bao1x = ["utralib/bao1x", "usb-bao1x/bao1x"]
board-dabao = [
    "bao1x-hal-service/board-dabao",
    "bao1x-hal/board-dabao",
    "usb-bao1x/board-dabao",
]
default = ["bao1x", "board-dabao"]
