// generate_map.js — run once: node generate_map.js
// Writes led_map.js with all 600 LED world positions pre-computed.
// Re-run only if the board geometry or composition layout changes.

'use strict';
const fs = require('fs');
const path = require('path');

// Exact positions from KiCad triangle.kicad_pcb (D1-D24, local board coords in mm)
const LOCAL_LEDS = [
  [108.66,     145        ], // D1  — bottom-left corner
  [118.995,    145        ], // D2
  [129.33,     145        ], // D3
  [139.665,    145        ], // D4
  [150,        145        ], // D5  — bottom midpoint
  [160.335,    145        ], // D6
  [170.67,     145        ], // D7
  [181.005,    145        ], // D8
  [191.34,     145        ], // D9  — bottom-right corner
  [186.1725,   136.049625 ], // D10
  [181.005,    127.09925  ], // D11
  [175.8375,   118.148875 ], // D12
  [170.67,     109.1985   ], // D13
  [165.5025,   100.248125 ], // D14
  [160.335,     91.29775  ], // D15
  [155.1675,    82.347375 ], // D16
  [150,         73.397    ], // D17 — top (apex) corner
  [144.8325,    82.347375 ], // D18
  [139.665,     91.29775  ], // D19
  [134.4975,   100.248125 ], // D20
  [129.33,     109.1985   ], // D21
  [124.1625,   118.148875 ], // D22
  [118.995,    127.09925  ], // D23
  [113.8275,   136.049625 ], // D24
];

// Local board centroid (from spec)
const LOCAL_CX = 150;
const LOCAL_CY = 121.132;

// Grid spacing with gap between board edges.
// In perfect tiling, adjacent board centroids are 100/√3 ≈ 57.735mm apart.
// Each 2mm gap between edges increases that distance by 2mm.
const BOARD_GAP = 2; // mm between each pair of touching board edges
const CENTROID_DIST = 100 / Math.sqrt(3); // 57.735mm, perfect tiling
const GRID_K = (CENTROID_DIST + BOARD_GAP) / CENTROID_DIST;
const H = 100 * Math.sqrt(3) / 2 * GRID_K; // row height, scaled
const STEP = 50 * GRID_K;                   // half-board x step, scaled

// Build composition table: 25 boards, top-to-bottom, left-to-right.
// Row r (1..5) has (11 - 2r) boards. Odd position = apex-down, even = apex-up.
const boards = [];
let boardId = 1;
for (let r = 1; r <= 5; r++) {
  const count = 11 - 2 * r;
  for (let p = 1; p <= count; p++) {
    const down = (p % 2 === 1);
    const cx = STEP * (r - 1 + p);
    const cy = down ? (3 * r - 2) / 3 * H : (3 * r - 1) / 3 * H;
    boards.push({ id: boardId++, row: r, pos: p, down, cx, cy });
  }
}

// Chain wiring: single daisy chain, right-to-left per row top-to-bottom, D1→D24 per board.
const CHAIN_ORDER = [9,8,7,6,5,4,3,2,1, 16,15,14,13,12,11,10, 21,20,19,18,17, 24,23,22, 25];
const BOARD_CHAIN_POS = {};
CHAIN_ORDER.forEach((boardId, pos) => { BOARD_CHAIN_POS[boardId] = pos; });

// Apply local→world transform for each board's 24 LEDs.
// Apex-up  (unrotated): wx = Cx + (lx - LOCAL_CX), wy = Cy + (ly - LOCAL_CY)
// Apex-down (180° rot): wx = Cx - (lx - LOCAL_CX), wy = Cy - (ly - LOCAL_CY)
function r3(v) { return Math.round(v * 1000) / 1000; }

const entries = [];
for (const board of boards) {
  for (let i = 0; i < LOCAL_LEDS.length; i++) {
    const [lx, ly] = LOCAL_LEDS[i];
    const dx = lx - LOCAL_CX;
    const dy = ly - LOCAL_CY;
    const wx = board.down ? board.cx - dx : board.cx + dx;
    const wy = board.down ? board.cy - dy : board.cy + dy;
    const chainIdx = BOARD_CHAIN_POS[board.id] * 24 + i;
    entries.push({ wx: r3(wx), wy: r3(wy), boardId: board.id, localIdx: i + 1, chainIdx });
  }
}

const lines = entries.map(e =>
  `  {wx:${e.wx},wy:${e.wy},boardId:${e.boardId},localIdx:${e.localIdx},chainIdx:${e.chainIdx}}`
);

const output = [
  '// Auto-generated by generate_map.js — do not edit by hand.',
  '// Source: triangel_lighting_design.md geometry + KiCad triangle.kicad_pcb LED positions.',
  `// ${entries.length} LEDs across ${boards.length} boards. Single chain, chainIdx 0–599.`,
  `const LED_MAP = [`,
  lines.join(',\n'),
  `];`,
  '',
].join('\n');

const outPath = path.join(__dirname, 'led_map.js');
fs.writeFileSync(outPath, output, 'utf8');
console.log(`Wrote ${outPath} (${entries.length} entries)`);
