// AUTOGENERATED CODE on 2026-07-22T21:21:32.112336 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(i2s_dma_bio_code, BM_I2S_DMA_BIO_START, BM_I2S_DMA_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "sw	s1, 4(sp)", // 4-byte Folded Spill
    "li	s1, 0",
    "li	a1, 0",
    "li	ra, 0",
    "li	a2, 14",
    "li	a5, 10",
    "li	s0, 4",
    "lui	a0, 397344",
    "li	t1, 32",
    "li	t2, -3",
    "li	a3, 2",
    // --- inline asm begin ---
    "mv	x26, a2",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, a5",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x25, s0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x22, a5",
    // --- inline asm end ---
    "sw	zero, -4(a0)",
    // --- inline asm begin ---
    "mv	a5, x16",
    // --- inline asm end ---
    "addi	a2, a5, 4",
    "sw	zero, 0(a5)",
    "li	s0, 24",
    "22:", // .LBB1_1: =>This Inner Loop Header: Depth=1
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beq	a1, t1, 24f",
    // in Loop: Header=BB1_1 Depth=1
    "li	a0, 1",
    "beq	a1, a0, 23f",
    // in Loop: Header=BB1_1 Depth=1
    "bnez	a1, 25f",
    // in Loop: Header=BB1_1 Depth=1
    "li	a0, -9",
    // --- inline asm begin ---
    "mv	x23, a0",
    // --- inline asm end ---
    "j	25f",
    "23:", // .LBB1_5: in Loop: Header=BB1_1 Depth=1
    "li	ra, 0",
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_1 Depth=1
    "li	a0, 8",
    // --- inline asm begin ---
    "mv	x22, a0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x23, t2",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	t0, x21",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x22, a3",
    // --- inline asm end ---
    "slli	t0, t0, 29",
    "srli	a4, t0, 31",
    "or	a4, a4, ra",
    "bne	a1, s0, 26f",
    // in Loop: Header=BB1_1 Depth=1
    // ERRATA BUG2 patch: slli	a0, s1, 20 (shamt=20)
    "slli a0, s1, 19",
    "slli a0, a0, 1",
    "addi	s1, s1, 1",
    "srli	a0, a0, 18",
    "add	a0, a0, a2",
    "sw	a4, 0(a0)",
    "sw	s1, 0(a5)",
    "26:", // .LBB1_9: in Loop: Header=BB1_1 Depth=1
    "slli	ra, a4, 1",
    "addi	a1, a1, 1",
    "srai	a0, a1, 31",
    "srli	a0, a0, 26",
    "add	a0, a0, a1",
    "andi	a0, a0, -64",
    "sub	a1, a1, a0",
    "j	22b"
);
