// AUTOGENERATED CODE on 2026-08-08T02:29:47.837792 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(i2s_bio_code, BM_I2S_BIO_START, BM_I2S_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "addi	sp, sp, -16",
    "sw	s0, 12(sp)", // 4-byte Folded Spill
    "li	a0, 0",
    "li	a2, 0",
    "li	t2, 14",
    "li	a4, 10",
    "li	a5, 4",
    "lui	a1, 4096",
    "li	t1, 1",
    "li	a3, 32",
    "li	t0, 8",
    // --- inline asm begin ---
    "mv	x26, t2",
    // --- inline asm end ---
    "addi	a1, a1, 1",
    // --- inline asm begin ---
    "mv	x24, a4",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x25, a5",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x22, a4",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x27, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x28, t1",
    // --- inline asm end ---
    "li	a5, -3",
    "li	a4, 2",
    "li	a1, 24",
    "li	t2, -9",
    "22:", // .LBB1_1: =>This Inner Loop Header: Depth=1
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beq	a0, a3, 24f",
    // in Loop: Header=BB1_1 Depth=1
    "beq	a0, t1, 23f",
    // in Loop: Header=BB1_1 Depth=1
    "bnez	a0, 25f",
    // in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x23, t2",
    // --- inline asm end ---
    "j	25f",
    "23:", // .LBB1_5: in Loop: Header=BB1_1 Depth=1
    "li	a2, 0",
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x22, t0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x23, a5",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	s0, x21",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x22, a4",
    // --- inline asm end ---
    "slli	s0, s0, 29",
    "srli	s0, s0, 31",
    "or	a2, a2, s0",
    "bne	a0, a1, 26f",
    // in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	s0, x30",
    // --- inline asm end ---
    "slli	s0, s0, 7",
    "bgez	s0, 26f",
    // in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x16, a2",
    // --- inline asm end ---
    "26:", // .LBB1_10: in Loop: Header=BB1_1 Depth=1
    "slli	a2, a2, 1",
    "addi	a0, a0, 1",
    "srai	s0, a0, 31",
    "srli	s0, s0, 26",
    "add	s0, s0, a0",
    "andi	s0, s0, -64",
    "sub	a0, a0, s0",
    "j	22b"
);
