mod audio;
// BIO programs for the I2S mic, vendored verbatim from bio-sim. Autogenerated -- do not edit.
// i2s_bio = FIFO capture (poll drain); i2s_dma = writes an IFRAM ring (drain-dma).
mod i2s_bio;
#[cfg(feature = "drain-dma")]
mod i2s_dma;
#[cfg(feature = "mel")]
mod mel;
mod pins;
mod uart_out;

use audio::{ActiveAudio, AudioSource};
use uart_out::UartOut;
// Without `mel`, main builds a level-only frame directly (the mel module isn't compiled).
#[cfg(not(feature = "mel"))]
use triangel_shared::mel::MelFrame;

fn main() -> ! {
    log_server::init_wait().unwrap();
    log::set_max_level(log::LevelFilter::Info);
    log::info!("ear starting, PID {}", xous::process::id());

    let hal = bao1x_hal_service::Hal::new();
    hal.set_preemption(true);

    let mut audio    = ActiveAudio::new();
    let mut uart_out = UartOut::new();

    log::info!("ear ready");

    // With the `mel` feature: run the FFT + 24-band mel filterbank on each frame and
    // send framed MelFrames to the eye. Otherwise: the temporary level path - a simple
    // RMS from each frame sent as one 0-255 byte.
    #[cfg(feature = "mel")]
    let mut processor = mel::MelProcessor::new();

    loop {
        let frame = audio.read_frame();
        #[cfg(feature = "mel")]
        uart_out.send(&processor.process(&frame));
        #[cfg(not(feature = "mel"))]
        {
            // Level-only frame from a simple RMS - same 53-byte wire format as the mel
            // path, just with the bands zeroed. 1.8 = sensitivity; higher = more.
            let rms = (frame.iter().map(|&s| (s as f32 / 32768.0).powi(2)).sum::<f32>()
                / frame.len() as f32).sqrt();
            let level = ((rms * 1.8).clamp(0.0, 1.0) * 65535.0) as u16;
            uart_out.send(&MelFrame::level_only(level, rms > 0.02));
        }
    }
}
