mod audio;
mod console;
mod diag;
// BIO program for the I2S mic, vendored verbatim from bio-sim. Autogenerated -- do not edit.
mod i2s_bio;
mod mel;
mod pins;
mod uart_out;

use audio::{FRAME_PERIOD_MS, I2sAudio};
use diag::Diag;
use uart_out::UartOut;

/// Frames averaged per timing measurement, and how far it must drift to be worth
/// reprinting. Steady state stays silent.
const MEL_TIMING_FRAMES: u32 = 32;
const MEL_REPORT_DELTA_MS: f32 = 1.0;

fn main() -> ! {
    // A panic anywhere prints over USB serial before the process dies; the USB
    // server owns the message once sent, so it still reaches the host. Without
    // this, a failed BIO resource claim in I2sAudio::new() is invisible.
    std::panic::set_hook(Box::new(|info| {
        Diag::new().line(&format!("PANIC: {}", info));
    }));

    // USB and the heartbeat come up before anything that can block, so a stalled
    // startup still reports the stage it stopped at.
    let d = Diag::new();
    diag::spawn_heartbeat();
    d.line("");
    d.line("=== ear ===");
    diag::stage(&d, 0);

    log_server::init_wait().unwrap();
    log::set_max_level(log::LevelFilter::Info);
    log::info!("ear starting, PID {}", xous::process::id());

    let hal = bao1x_hal_service::Hal::new();
    hal.set_preemption(true);
    diag::stage(&d, 1);

    let tt = ticktimer::Ticktimer::new().unwrap();

    d.line("I2S pins: PB1 = BCLK, PB2 = SD, PB3 = WS");
    diag::stage(&d, 2);
    let mut mic = I2sAudio::new();
    diag::stage(&d, 3);

    let mut uart_out = UartOut::new();

    d.line(&format!("FIFO0 level {}", mic.fifo_level()));
    console::help(&d);
    console::spawn();
    diag::stage(&d, 4);

    log::info!("ear ready");

    // Run the 24-band mel filterbank on each frame and send framed MelFrames to the eye.
    let mut processor = mel::MelProcessor::new();
    // Filterbank cost, averaged over a batch - the ticktimer only resolves ms.
    let (mut mel_ms, mut mel_frames) = (0u64, 0u32);
    let mut mel_reported: Option<f32> = None;
    let mut starved_reported = 0u32;

    loop {
        // The mic is not Send, so diagnostic commands run here rather than on the
        // console thread. Returns immediately when no key has been pressed.
        console::service(&d, &tt, &mut mic);

        let frame = mic.read_frame();

        // The eye cannot tell a starved frame from a quiet room, so say so.
        let starved = mic.starved_frames();
        if starved != starved_reported {
            d.line(&format!("mic starved: {} frames abandoned, the BIO stopped pushing", starved));
            starved_reported = starved;
        }

        let started = tt.elapsed_ms();
        let processed = processor.process(&frame);
        mel_ms += tt.elapsed_ms() - started;
        uart_out.send(&processed);

        mel_frames += 1;
        if mel_frames == MEL_TIMING_FRAMES {
            let per_frame = mel_ms as f32 / MEL_TIMING_FRAMES as f32;
            console::record_mel_time((per_frame * 1000.0) as u32);
            if mel_reported.is_none_or(|last| (per_frame - last).abs() > MEL_REPORT_DELTA_MS) {
                d.line(&format!("mel: {:.2} ms per frame, budget {} ms", per_frame, FRAME_PERIOD_MS));
                mel_reported = Some(per_frame);
            }
            mel_ms = 0;
            mel_frames = 0;
        }
    }
}
