#!/usr/bin/env python3
"""Generate src/led/geom.rs: per-LED distances and angles from fixed points on the fixture.

Reads the world constants and LED positions out of src/led/map.rs so the geometry has one
source of truth. Re-run if map.rs changes.

    python tools/gen_geom.py
"""

import math
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "src" / "led" / "map.rs"
GRID = ROOT / "src" / "led" / "grid.rs"
OUT = ROOT / "src" / "led" / "geom.rs"

PER_LINE = 6
IDX_PER_LINE = 16


def const(src: str, name: str, ty: str = "f32") -> float:
    m = re.search(rf"const {name}: {ty}\s*=\s*([-0-9.]+)\s*;", src)
    if not m:
        raise SystemExit(f"could not find constant {name}")
    return float(m.group(1))


def as_f32(v: float) -> float:
    """Round a Python float to the nearest f32, the value Rust will hold."""
    return struct.unpack("<f", struct.pack("<f", v))[0]


def dist_f32(dx: float, dy: float) -> float:
    """Mirror map.rs `dist_to`, rounding to f32 at each step so the value matches the device."""
    d2 = as_f32(as_f32(dx * dx) + as_f32(dy * dy))
    return as_f32(math.sqrt(d2))


def lit(v: float) -> str:
    """Shortest Rust f32 literal that still parses back to exactly this value."""
    target = as_f32(v)
    s = repr(target)
    for digits in range(1, 10):
        candidate = f"{target:.{digits}g}"
        if as_f32(float(candidate)) == target:
            s = candidate
            break
    if not any(c in s for c in ".eE"):
        s += ".0"
    return s


def emit(name: str, doc: str, values: list[str]) -> list[str]:
    lines = [f"/// {doc}", f"pub static {name}: [f32; LED_COUNT] = ["]
    for start in range(0, len(values), PER_LINE):
        lines.append("    " + ", ".join(values[start : start + PER_LINE]) + ",")
    lines += ["];", ""]
    return lines


def emit_u16(name: str, ty: str, doc: str, values: list[int]) -> list[str]:
    lines = [f"/// {doc}", f"pub static {name}: {ty} = ["]
    for start in range(0, len(values), IDX_PER_LINE):
        lines.append("    " + ", ".join(str(v) for v in values[start : start + IDX_PER_LINE]) + ",")
    lines += ["];", ""]
    return lines


def buckets(leds: list[tuple[str, str]], cell_mm: float, cols: int, rows: int):
    """Group LED indices by grid cell, mirroring the bucketing in grid.rs."""
    cells: list[list[int]] = [[] for _ in range(cols * rows)]
    for i, (wx_s, wy_s) in enumerate(leds):
        wx, wy = as_f32(float(wx_s)), as_f32(float(wy_s))
        cx = min(int(as_f32(wx / cell_mm)), cols - 1)
        cy = min(int(as_f32(wy / cell_mm)), rows - 1)
        cells[cy * cols + cx].append(i)

    start, flat = [0], []
    for cell in cells:
        flat.extend(cell)
        start.append(len(flat))
    return start, flat


def main() -> None:
    src = MAP.read_text(encoding="utf-8")
    grid_src = GRID.read_text(encoding="utf-8")

    cell_mm = const(grid_src, "CELL_MM")
    cols = int(const(grid_src, "COLS", "usize"))
    rows = int(const(grid_src, "ROWS", "usize"))

    cx = const(src, "WORLD_CX")
    top = const(src, "WORLD_TOP")
    bot = const(src, "WORLD_BOT")
    # Mirrors WORLD_CENTROID_X / WORLD_CENTROID_Y in map.rs.
    centroid_x = cx
    centroid_y = as_f32(top + as_f32(as_f32(bot - top) / 3.0))

    leds = re.findall(r"Led\s*\{\s*wx:\s*([-0-9.]+),\s*wy:\s*([-0-9.]+)", src)
    if not leds:
        raise SystemExit(f"no LED entries found in {MAP}")

    dist_c, theta_c, dist_apex = [], [], []
    for wx_s, wy_s in leds:
        wx, wy = as_f32(float(wx_s)), as_f32(float(wy_s))

        dx, dy = as_f32(wx - centroid_x), as_f32(wy - centroid_y)
        dist_c.append(lit(dist_f32(dx, dy)))
        theta_c.append(lit(math.atan2(dy, dx)))

        ax, ay = as_f32(wx - cx), as_f32(wy - bot)
        dist_apex.append(lit(dist_f32(ax, ay)))

    cell_start, cell_leds = buckets(leds, cell_mm, cols, rows)

    body = "\n".join(
        [
            "// Auto-generated by tools/gen_geom.py from map.rs - do not edit by hand.",
            "// Per-LED geometry and the spatial grid buckets.",
            "",
            "use super::grid::{COLS, ROWS};",
            "use super::map::LED_COUNT;",
            "",
            *emit("DIST_C", "Distance in mm from the fixture centroid.", dist_c),
            *emit("THETA_C", "Angle in radians from the fixture centroid.", theta_c),
            *emit("DIST_APEX", "Distance in mm from the apex, the triangle's low point.", dist_apex),
            *emit_u16(
                "CELL_START",
                "[u16; COLS * ROWS + 1]",
                "Where each grid cell's run begins in CELL_LEDS.",
                cell_start,
            ),
            *emit_u16(
                "CELL_LEDS",
                "[u16; LED_COUNT]",
                "LED indices grouped by grid cell, ascending within each cell.",
                cell_leds,
            ),
        ]
    )
    OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUT} ({len(leds)} LEDs, {cols}x{rows} grid)")


if __name__ == "__main__":
    main()
