#!/usr/bin/env python3
"""Generate src/led/geom.rs: per-LED distances and angles from fixed points on the fixture.

Reads the world constants and LED positions out of src/led/map.rs so the geometry has one
source of truth. Re-run if map.rs changes.

    python tools/gen_geom.py
"""

import math
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "src" / "led" / "map.rs"
OUT = ROOT / "src" / "led" / "geom.rs"

PER_LINE = 6


def const(src: str, name: str) -> float:
    m = re.search(rf"pub const {name}: f32\s*=\s*([-0-9.]+)\s*;", src)
    if not m:
        raise SystemExit(f"could not find constant {name} in {MAP}")
    return float(m.group(1))


def as_f32(v: float) -> float:
    """Round a Python float to the nearest f32, the value Rust will hold."""
    return struct.unpack("<f", struct.pack("<f", v))[0]


def dist_f32(dx: float, dy: float) -> float:
    """Mirror map.rs `dist_to`, rounding to f32 at each step so the value matches the device."""
    d2 = as_f32(as_f32(dx * dx) + as_f32(dy * dy))
    return as_f32(math.sqrt(d2))


def lit(v: float) -> str:
    """Shortest Rust f32 literal that still parses back to exactly this value."""
    target = as_f32(v)
    s = repr(target)
    for digits in range(1, 10):
        candidate = f"{target:.{digits}g}"
        if as_f32(float(candidate)) == target:
            s = candidate
            break
    if not any(c in s for c in ".eE"):
        s += ".0"
    return s


def emit(name: str, doc: str, values: list[str]) -> list[str]:
    lines = [f"/// {doc}", f"pub static {name}: [f32; LED_COUNT] = ["]
    for start in range(0, len(values), PER_LINE):
        lines.append("    " + ", ".join(values[start : start + PER_LINE]) + ",")
    lines += ["];", ""]
    return lines


def main() -> None:
    src = MAP.read_text(encoding="utf-8")

    cx = const(src, "WORLD_CX")
    top = const(src, "WORLD_TOP")
    bot = const(src, "WORLD_BOT")
    # Mirrors WORLD_CENTROID_X / WORLD_CENTROID_Y in map.rs.
    centroid_x = cx
    centroid_y = as_f32(top + as_f32(as_f32(bot - top) / 3.0))

    leds = re.findall(r"Led\s*\{\s*wx:\s*([-0-9.]+),\s*wy:\s*([-0-9.]+)", src)
    if not leds:
        raise SystemExit(f"no LED entries found in {MAP}")

    dist_c, theta_c, dist_apex = [], [], []
    for wx_s, wy_s in leds:
        wx, wy = as_f32(float(wx_s)), as_f32(float(wy_s))

        dx, dy = as_f32(wx - centroid_x), as_f32(wy - centroid_y)
        dist_c.append(lit(dist_f32(dx, dy)))
        theta_c.append(lit(math.atan2(dy, dx)))

        ax, ay = as_f32(wx - cx), as_f32(wy - bot)
        dist_apex.append(lit(dist_f32(ax, ay)))

    body = "\n".join(
        [
            "// Auto-generated by tools/gen_geom.py from map.rs - do not edit by hand.",
            "// Per-LED distances and angles from fixed points on the fixture.",
            "",
            "use super::map::LED_COUNT;",
            "",
            *emit("DIST_C", "Distance in mm from the fixture centroid.", dist_c),
            *emit("THETA_C", "Angle in radians from the fixture centroid.", theta_c),
            *emit("DIST_APEX", "Distance in mm from the apex, the triangle's low point.", dist_apex),
        ]
    )
    OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUT} ({len(leds)} LEDs, 3 tables)")


if __name__ == "__main__":
    main()
