// AUTOGENERATED CODE on 2026-08-06T00:52:13.191981 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(nec_rx_bio_code, BM_NEC_RX_BIO_START, BM_NEC_RX_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "addi	sp, sp, -32",
    "sw	ra, 28(sp)", // 4-byte Folded Spill
    "sw	s0, 24(sp)", // 4-byte Folded Spill
    "sw	s1, 20(sp)", // 4-byte Folded Spill
    "li	s0, 0",
    "li	s1, 0",
    "lui	a0, 262144",
    // --- inline asm begin ---
    "mv	a1, x16",
    // --- inline asm end ---
    "addi	a0, a0, -1",
    // --- inline asm begin ---
    "mv	x26, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x25, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a2, x16",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a1, x16",
    // --- inline asm end ---
    "sw	a1, 12(sp)", // 4-byte Folded Spill
    // --- inline asm begin ---
    "mv	a4, x16",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a3, x16",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a5, x16",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a1, x31",
    // --- inline asm end ---
    "and	t1, a1, a0",
    "li	t2, 1",
    "li	ra, -1",
    "22:", // .LBB1_1: =>This Loop Header: Depth=1
    // Child Loop BB1_2 Depth 2
    // Child Loop BB1_3 Depth 3
    "sw	s0, 16(sp)", // 4-byte Folded Spill
    "mv	s0, s1",
    "23:", // .LBB1_2: Parent Loop BB1_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB1_3 Depth 3
    "mv	s1, t1",
    "24:", // .LBB1_3: Parent Loop BB1_1 Depth=1
    // Parent Loop BB1_2 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a1, x31",
    // --- inline asm end ---
    "and	t1, a1, a0",
    "mv	a1, t2",
    "bltu	t1, s1, 25f",
    // in Loop: Header=BB1_3 Depth=3
    "neg	t0, s1",
    "j	26f",
    "25:", // .LBB1_5: in Loop: Header=BB1_3 Depth=3
    "xor	t0, s1, a0",
    "26:", // .LBB1_6: in Loop: Header=BB1_3 Depth=3
    "add	t0, t0, t1",
    "li	t2, 1",
    "mv	s1, t1",
    "bltu	t0, a2, 24b",
    // in Loop: Header=BB1_3 Depth=3
    "mv	s1, t1",
    "bgeu	t0, a5, 24b",
    // in Loop: Header=BB1_3 Depth=3
    "bgeu	t0, a4, 27f",
    // in Loop: Header=BB1_3 Depth=3
    "andi	a1, a1, 1",
    "mv	s1, t1",
    "bnez	a1, 24b",
    "j	28f",
    "27:", // .LBB1_10: in Loop: Header=BB1_3 Depth=3
    "bgeu	t0, a3, 29f",
    // in Loop: Header=BB1_3 Depth=3
    "andi	a1, a1, 1",
    "mv	s1, t1",
    "beqz	a1, 24b",
    // in Loop: Header=BB1_2 Depth=2
    // --- inline asm begin ---
    "mv	x16, ra",
    // --- inline asm end ---
    "j	23b",
    "28:", // .LBB1_13: in Loop: Header=BB1_1 Depth=1
    "li	t2, 0",
    "srli	a1, s0, 1",
    "lw	s1, 12(sp)", // 4-byte Folded Reload
    "sltu	s1, t0, s1",
    "not	s1, s1",
    "slli	s1, s1, 31",
    "lw	s0, 16(sp)", // 4-byte Folded Reload
    "addi	s0, s0, 1",
    "or	s1, s1, a1",
    "li	a1, 32",
    "bne	s0, a1, 22b",
    // in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x16, s1",
    // --- inline asm end ---
    "li	t2, 1",
    "li	s0, 32",
    "j	22b",
    "29:", // .LBB1_15: in Loop: Header=BB1_1 Depth=1
    "li	s0, 0",
    "li	t2, 0",
    "li	s1, 0",
    "j	22b"
);
